### ISSUE TITLE
Can't use cordova-plugin-background-mode

### ISSUE THREAD

**Issue by jwliang1226** [WebsiteBeaver/CordovaCall#10]
Hi all,
All Questions are on IOS 11, test on real phone(iphone6s plus).
Question 1 
I'm using cordova-plugin-background-mode with CordovaCall, the following  are  my pseudo code:
1: cordova.plugins.backgroundMode.enable();
2: Coming Call.
3: cordova.plugins.CordovaCall.receiveCall("jwliang2226");
4: User press "ACCEPT" to chat.
5: cordova.plugins.CordovaCall.endcall();
6. User press iphone power button to sleep.
7. Javascript into sleep(??)
8. Someone call is coming but Javascript is sleeping, so Callkit can not start!
cordova.plugins.backgroundMode.enable()  not function anymore, even I do it again, background can not be re-enable.

Question 2 
cordova.plugins.CordovaCall.on('answer', function() {
    /* I will into "answer event" several times  when I accept a receiveCall once. */
    console.log("Into answer event");
});

Question 3
I'm using jssip and cordova-plugin-iosrtc with this plugin(CordovaCall),  I do cordova.plugins.CordovaCall.receiveCall() and local streaming(iphone camera) is works perfectly at first time, but do cordova.plugins.CordovaCall.receiveCall at several time the local streaming(iphone camera) will show black screen.(Can't open camera successfully)

[debug log]
[avas] AVAudioSession.mm:1177:-[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

I have no error without CordovaCall plugin. When I use CordovaCall plugin I can't release my camera device?

My camera release code:
            var selfView = document.getElementById('localVideo');
            var remoteView = document.getElementById('remoteVideo');
            selfView.pause();
            remoteView.pause();
            selfView.src = "";
            remoteView.src = "";
            session.connection.getLocalStreams()[0].getTracks()[0].stop();
            remoteStream.getTracks()[0].stop();

I have no error without CordovaCall plugin and release code.

Thanks for your review:)

**Comment by dmarcs** [comment]
**Question 1**
If you close your app and turn off your phone, and you call the phone using your video chat app, you'll notice that nothing happens. You need to use [PushKit](https://developer.apple.com/documentation/pushkit) to solve the problem. Here's a good Cordova plugin for PushKit https://github.com/Hitman666/cordova-ios-voip-push. We're thinking about building this into CordovaCall in a future version.

**Question 2**
Did you call `cordova.plugins.CordovaCall.on('answer', handler);` more than once? That's a very common mistake. If you call it three times, it will get executed three times.

**Question 3**
This sounds like an issue with iosRTC. It's possible that you didn't free the camera successfully. Take a look at https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/issues/140. I posted a function called freeCamera that fixed a similar issue I had.

**Comment by jwliang1226** [comment]
Hi @dmarcs 
Question 1
My app uses jssip(Javascript SIP) and needs to be constantly connected to the server without interruption, it seems that there is no way to use pushkit？ Is there any way to use the plugin cordova-plugin-background-mode? 

Question 2   resolved
Question 3   resolved

**Comment by dmarcs** [comment]
@jwliang1226 That's great to hear that you solved two of your problems. Please share how you solved both Question 2 and Question 3 so it could help someone in the future with a similar problem 😃

I would recommend to stop using the the Cordova background mode plugin. There's no need to use it for a video chat app, and it won't help you if the app is closed and the phone is off. In this case you won't be able to receive a call. You have no choice, but to use PushKit. No other Cordova plugin will solve this problem. I assume you're using a wss Node.js server, which is fine. You don't need the phone to remain connected to the Node.js server if the app gets force quit. PushKit lets you wake up the app (temporarily) even if it has been force quit. At this point you can call CordovaCall methods followed by iosRTC methods to start the video chat.

**Comment by jwliang1226** [comment]
@dmarcs 
Question 2  
I did call cordova.plugins.CordovaCall.on('answer', handler); many times, so it result the problem.
Question 3 
"freeCamera" can resolves the issue.

Question 1
iPhone 1 <-> websocket <-> sip server(kamailio) <-> websocket  <-> iPhone 2

Any incoming calls are forwarded via sip server,
If there is a phone call came in, but the iphone is sleeping, the current connection is disconnected, sip server how to use pushkit to help me forward the phone? I'm not familiar with the usage of pushkit :(

**Comment by dmarcs** [comment]
@jwliang1226 Have you ever used regular push notifications? If you have, it's very similar. The difference between regular push notifications and PushKit is that PushKit is meant only for VOIP (video chat, audio chat) apps. Apple made it to solve the problem you're having. Go to the cordova-ios-voip-push docs to see how to set it up. It's very easy to use. You need an Apple developer account because PushKit only works if you get a certificate from the Apple developer website. PushKit will wake up your app temporarily so that you can reconnect it to the sip server and make the video chat work.

**Comment by jwliang1226** [comment]
@dmarcs OK, I will study the docs,  thank you very much.
