### ISSUE TITLE
Can't set speakerphone on/off at first call. 

### ISSUE THREAD

**Issue by jwliang1226** [WebsiteBeaver/CordovaCall#11]
I'm using webrtc and CordovaCall, I tried to set speakerphone on/off by cordova-plugin-audioroute or cordova-plugin-audiotoggle, but not functional at first receiveCall. Second receiveCall works well.

I have no error without receiveCall.

**Comment by D-Marc1** [comment]
This plugin currently does not give you control over audio. I actually opened this issue as a feature request.
