### ISSUE TITLE
VOIP Config

### ISSUE THREAD

**Issue by rochapablo** [WebsiteBeaver/CordovaCall#15]
Where should I config the voip?

**Comment by D-Marc1** [comment]
This plugin is currently just the native call UI for iOS and Android. This would be used in a VoIP app, but this plugin has nothing to do with that. To wake up the app on iOS you would use PushKit; on Android you'd send a silent push notification. For the VoIP part you'd use something like Socket.io or Firebase.

**Comment by rochapablo** [comment]
Suppose that VOIP it's already working, which both devices are able to communicate, in which time the **native call UI** should be opened?

Because when I do the call, the **native call UI** opens and close saying that was disconnect while the VOIP still on.

**Comment by D-Marc1** [comment]
Can you please show your code?

**Comment by rochapablo** [comment]
Besides all the setup, right after I start a VOIP call, I call this

```
Uri uri = Uri.fromParts("tel", params.getString("To"), null);
Bundle callInfoBundle = new Bundle();
callInfoBundle.putString("to", params.getString("To"));
Bundle callInfo = new Bundle();
callInfo.putParcelable(TelecomManager.EXTRA_OUTGOING_CALL_EXTRAS,callInfoBundle);
callInfo.putParcelable(TelecomManager.EXTRA_PHONE_ACCOUNT_HANDLE, handle);
tm.placeCall(uri, callInfo);
tm.showInCallScreen(true);
Log.d(TAG,"Outgoing call successful");
```

[Here](https://stackoverflow.com/questions/47942487/android-connectionservice-with-twilio) I have an open questions about it.

**Comment by D-Marc1** [comment]
Sorry, I'm a bit confused why you're messing with the native Android code. This plugin is meant to be used in Cordova for the JavaScript wrapper. I'm also even more confused that your question is about React Native.

**Comment by rochapablo** [comment]
I'm messing with the native Android code, because there's no much documentation about ConnectionService and CordovaCall it's the closest I can get.

I understand that this is meant to be used in Cordova; What I am doing is re-writing to use on React Native; but the communication between javascript and Android code it's the big deal. The real struggle it's understand how to implement ConnectionService to the VOIP.

So, as you create the CordovaCall I was hopping that you could guide in this implementation; because even running the CordovaCall alone I see that it's working as the screenshots but I still missing the VOIP setup.

**Comment by jimmyappspace** [comment]
I have some question.
Is this cordova plugin using Telco or RTC to make a call?
Also, sendCall('Daniel Marcus') function, Daniel Marcus is the Name in the contact list?
I plan to use Ionic framework to develop RTC function which allow users make a intercom call, does this plugin suitable for my use case?
