### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by Steco17** [WebsiteBeaver/CordovaCall#19]
Hello, whenever i launch the plug-in on my command it does exit with an error. as bellow
![captureerror](https://user-images.githubusercontent.com/16323355/35390397-9422409c-01db-11e8-877f-b8504257cfe2.JPG)

**Comment by D-Marc1** [comment]
Hmm... I'm not really sure what to tell you, as I can't reproduce this. Are you adding the plugin in your Cordova directory? Maybe try adding it to a new project. Could be something in your current one that's conflicting with it.

**Comment by Steco17** [comment]
@D-Marc1 thanks i fix it. was an issue with my project as you said
