### ISSUE TITLE
WebRTC intergration.

### ISSUE THREAD

**Issue by Moyo17** [WebsiteBeaver/CordovaCall#20]
Hello,
Following the example from https://websitebeaver.com/insanely-simple-webrtc-video-chat-using-firebase-with-codepen-demo i have difficulties integrating CordovaCall with that demo for both audio and video call. please i need help with this. The instructions you gave is not that explicit.
thanks

**Comment by dmarcs** [comment]
Hi @Moyo17 please take a look at [https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc](iosrtc). It's a Cordova plugin that lets you create a video chat on mobile using WebRTC. WebRTC already works on Android without a Cordova plugin, but it doesn't work on iOS (although it does work on mobile Safari). So this plugin makes WebRTC work on iOS.

The code from [https://websitebeaver.com/insanely-simple-webrtc-video-chat-using-firebase-with-codepen-demo](https://websitebeaver.com/insanely-simple-webrtc-video-chat-using-firebase-with-codepen-demo) works on computer, mobile Safari, and Android. It doesn't work on iOS apps without using iosrtc.
