### ISSUE TITLE
off('event') or unsubscribe

### ISSUE THREAD

**Issue by HugoHeneault** [WebsiteBeaver/CordovaCall#23]
I'm receiving different calls by push notification, with different params for each of them: 
```ts
     pushObject.on('notification').subscribe((data: any) => {
          cordova.plugins.CordovaCall.receiveCall(data.additionalData.username);

          cordova.plugins.CordovaCall.on('answer', () => {
              this.handleDeeplink(data);
          });
      });
```

As I'm setting the `CordovaCall.on('answer')` at every push reception, I need to unbind it before setting it again. But I don't think there is a `off()` method. 

Or maybe there is another way of handling it?

Thanks!

**Comment by D-Marc1** [comment]
I'm confused why the event handler `cordova.plugins.CordovaCall.on('answer')` is inside of your push notification handler. Nesting event handlers is generally not a good idea.

**Comment by dmarcs** [comment]
@D-Marc1 is right. Your code should look like this:

```
pushObject.on('notification').subscribe((data: any) => {
});

cordova.plugins.CordovaCall.receiveCall(data.additionalData.username);

cordova.plugins.CordovaCall.on('answer', () => {
     this.handleDeeplink(data);
});
```

That being said, I do think that we should implement an `off` method in a future release.
