### ISSUE TITLE
fail while build - cannot find symbol  .setCapabilities(PhoneAccount.CAPABILITY_SELF_MANAGED)

### ISSUE THREAD

**Issue by overmindx1** [WebsiteBeaver/CordovaCall#27]
Install plugin is no problem, but build app is failed .
android-minSdkVersion is setting to 23 , Android 6.
How can I fix this ?

![1520585551956](https://user-images.githubusercontent.com/10805626/37198757-528f9e44-23ba-11e8-8c6f-e94f5f3f0090.jpg)

**Comment by dmarcs** [comment]
@overmindx1 Please upgrade to the latest Android SDK

**Comment by D-Marc1** [comment]
In case it isn't clear, David means upgrading in Android Studio. The earliest cordova-android version you should have is 6.2.3, [as stated here](https://cordova.apache.org/announcements/2017/05/04/android-release.html).

**Comment by overmindx1** [comment]
Thank you all you guys for fast reply .

I updated my Android SDK  and Cordova .
but still get same situation .

I put some picture of my Android SDK and Cordova setting .

![1](https://user-images.githubusercontent.com/10805626/37240360-25d4fdc4-2485-11e8-9675-6c785e67db97.jpg)
![2](https://user-images.githubusercontent.com/10805626/37240361-25fc4e1a-2485-11e8-98bb-77d24bfc2b5a.jpg)
![3](https://user-images.githubusercontent.com/10805626/37240362-26297548-2485-11e8-91ee-c5383d49e137.jpg)
![4](https://user-images.githubusercontent.com/10805626/37240363-26589620-2485-11e8-84cc-7e15fb410424.jpg)

Am I miss some thing to fix this problem?
Thanks  .

**Comment by dmarcs** [comment]
@overmindx1 Open up your project in Android Studio. Then go to `File` -> `Project Structure`. Change the `Compile Sdk Version` to 26 or higher. As you can see, mine is set to 27.

<img width="820" alt="android_sdk" src="https://user-images.githubusercontent.com/26162804/37249475-25895f8c-24b6-11e8-963f-6669eceff462.png">

**Comment by overmindx1** [comment]
I create new Cordova App , using Android 7.0 , working fine now .
Thank you 👍

**Comment by D-Marc1** [comment]
I'm glad. Should work fine on Android 6 as well.
