### ISSUE TITLE
Screen During Call not show when i tap "Accept" IOS

### ISSUE THREAD

**Issue by stove654** [WebsiteBeaver/CordovaCall#31]
Hi, I'm using IphoneSE and ios11. when i call function `cordova.plugins.CordovaCall.receiveCall('David Marcus')` it show Screen Wait Accept but when i tab Accept will hide it. but i'm sure it running but not show Screen During Call.
- IOS 11, IphoneSE, cordova@6.5.0
Can you help me?

**Comment by D-Marc1** [comment]
I don't understand what the issue is, but [this video](https://www.youtube.com/watch?v=06svKrE1lJ8) should help show you the intended result of using CallKit.

**Comment by stove654** [comment]
@D-Marc1 you have source code demo like video. can you send me.

**Comment by D-Marc1** [comment]
The examples in the docs should get you started out with using CordovaCall. Try it out and see if it works. Then use it to adapt to your needs, whether it be a WebRTC video or audio chat.
