### ISSUE TITLE
Android device "recent calls" are all "Unknown"

### ISSUE THREAD

**Issue by rcorrie** [WebsiteBeaver/CordovaCall#35]
Thanks for the component!
I have got it working well except for this one issue. All the calls I receive to my voip app are showing up as "Unknown" in the device's native Recent Calls app.

I am calling `cordova.plugins.CordovaCall.receiveCall('BOB');`

The incoming notification looks good:
<img width="361" alt="screen shot 2018-04-20 at 10 04 11 pm" src="https://user-images.githubusercontent.com/6488063/39079389-c12ffcf6-44e7-11e8-8a02-7dd454072fd2.png">

But then once it view it in the log, it's shows "Unknown" instead of "BOB":
<img width="345" alt="screen shot 2018-04-20 at 10 04 24 pm" src="https://user-images.githubusercontent.com/6488063/39079398-d05f8520-44e7-11e8-9116-c54f3bf59216.png">

Edit: In the worst case scenario, I rather nothing show up on the "Recent Calls" log, anyway of doing this?

**Comment by D-Marc1** [comment]
Hey @rcorrie, unfortunately Android doesn't give you control over changing the recent call name. There's also no way of preventing it from going in there the first place.

Android ConnectionService needs to catch up to iOS CallKit in many ways, and this is certainly an area it needs to improve in. It's not very intuitive to just have 'Unknown' show up in your recent calls.

**Comment by rcorrie** [comment]
Thanks for the reply, and again thanks for the awesome work. Yeah it's a shame that Android hasn't gotten around to better documenting and fleshing out this API.

What I ended up doing is writing a `BroadcastReceiver` that will watch the phone state. Whenever the phone state changes to idle, it deletes any call log item matching my phoneAccount ID. The downside is that we need to ask for write permissions for the call log.

**Comment by D-Marc1** [comment]
I can't take credit for this amazing plugin, as this is all @dmarcs' hard work.

It's actually quite shocking how terrible the implementation is of ConnectionService. If I'm not mistaken, Google Hangouts doesn't even use it, ironically. Hopefully they'll fix most of its issues next version.

That's a good idea, and we've thought of doing that too. It's really a tradeoff type of situation.

**Comment by D-Marc1** [comment]
Ya, you would think so, considering they all use CallKit for iOS. Even Google doesn't bother with its own creation.

TBH, the best solution for Android is to force open your app and create a custom answering dialogue. This is what they all use currently. ConnectionService has a lot of potential, but they decided to not give much thought to it, along with poorly documenting it.

**Comment by andrewvmail** [comment]
Yo @rcorrie check out #36
