### ISSUE TITLE
Endcall Function is not working

### ISSUE THREAD

**Issue by videmort** [WebsiteBeaver/CordovaCall#44]
If i execute for example
cordova.plugins.CordovaCall.receiveCall('Me');

It launch OK the secreen to decline or response

If I response and call later in my app the function

cordova.plugins.CordovaCall.endCall();
Nothing happened. The native screen call is active all time and when I close my app it show "Error call"

to reproduce the error

```
cordova.plugins.CordovaCall.receiveCall('Me');

cordova.plugins.CordovaCall.on('answer', () => {

      setTimeout(() => { // 5 sec to end call
         cordova.plugins.CordovaCall.endCall();
      }, 5000);
  
  });

```

**Comment by dmarcs** [comment]
@videmort 

Thanks for sharing your code. Here's what I get when I run it on my iPhone.

![endcall-cordovacall](https://user-images.githubusercontent.com/26162804/41910649-4fb8e906-7918-11e8-9363-f31b04fc77b7.gif)

As you can see, the call ends after 5 seconds as expected. Is there a call in progress when you call `receiveCall`? Can you run your project in Xcode and let me know the error message you get? I understand that you get the "Error call" message on your iPhone, but that can happen for several reasons. Xcode might have a more detailed error message.

**Comment by dmarcs** [comment]
@videmort Let me know if you got this to work. As you can see in my example above, `endCall` works fine. My guess is that you have other code that's causing this to fail. I would recommend doing what I did, which is to create a new project and run your code.

**Comment by videmort** [comment]
Hi dmarcs ! This is the error -->
No se ha podido completar la operación. (Error de com.apple.CallKit.error.requesttransaction 4.)

**Comment by videmort** [comment]
https://stackoverflow.com/questions/46090002/callkit-call-end-issueerror-domain-com-apple-callkit-error-requesttransaction-c

**Comment by videmort** [comment]
<img width="784" alt="captura de pantalla 2018-07-25 a las 0 17 46" src="https://user-images.githubusercontent.com/11390548/43169164-52b88c44-8fa0-11e8-8c48-9faaf8c5fe54.png">
@dmarcs  property UUID doesn't exist
