### ISSUE TITLE
Is it possible to have dtmf event on android phone

### ISSUE THREAD

**Issue by arekfryz** [WebsiteBeaver/CordovaCall#49]
Is it possible to trigger dtmf event on android phone like it does on iOS?

Thank you,
Arek

**Comment by D-Marc1** [comment]
Yes, but it's not currently implemented in this plugin.

**Comment by arekfryz** [comment]
@D-Marc1 
If you are interested, I have pushed commit that exposes dtmf event in android. Also, call from recent/contacts/dialer was broken for me on Samsung phone and I added solution for it. 
DTMF added on outbound call only.

**Comment by D-Marc1** [comment]
Ya for sure, thank you! We're a bit busy currently, but we'll review it when we have a chance if you send a PR.
