### ISSUE TITLE
How to hide "in-call screen" or get app to foreground.

### ISSUE THREAD

**Issue by erayturan** [WebsiteBeaver/CordovaCall#50]
How to get app to foreground after "answer" in-call screen? Is it possible!

**Comment by D-Marc1** [comment]
That's what actually happens.

**Comment by bpowell15** [comment]
im finding that this is not the behavior of this plugin anymore.. not sure what has changed.. but i can no longer get video calls to work bc my app ends up behind the native calling ui

**Comment by ShahidNaumanTEO** [comment]
> im finding that this is not the behavior of this plugin anymore.. not sure what has changed.. but i can no longer get video calls to work bc my app ends up behind the native calling ui

I am experiencing the same. :-(
