### ISSUE TITLE
How to show "ongoing call" UI after call got accepted?

### ISSUE THREAD

**Issue by BorntraegerMarc** [WebsiteBeaver/CordovaCall#53]
How to show "ongoing call" UI after call got accepted? At the moment the plugin automatically shows the normal cordova app but I would like to show the native "ongoing call" UI so the user sees that the call is on going.

**Comment by D-Marc1** [comment]
This seems to be one of the most misunderstood  aspects of CallKit. It's meant to be used for the native call dialogue, but ultimately, you need to have your own call UI as well. Try out Skype, Hangouts, WhatsApp, Facebook, etc., and you'll see that's how they do it.

**Comment by BorntraegerMarc** [comment]
Thanks for pointing it out. I wonder if so many misunderstand the plug-in because of the dead simple examples? I basically just copy/ pasted them and didn't see the expected result...

Is it also the intended behavior to not show any UI when calling the method `sendCall`?

**Comment by BorntraegerMarc** [comment]
I described my issue a bit better in this github issue: https://github.com/WebsiteBeaver/CordovaCall/issues/52.
No need to continue the conversation in here as there are 2 different things

**Comment by jonybuzz** [comment]
@D-Marc1 I didn´t get something... Does the plugin allow me to show a custom UI? i.e. integrate it with existing app UI
