### ISSUE TITLE
Add ability to call a number

### ISSUE THREAD

**Issue by D-Marc1** [WebsiteBeaver/CordovaCall#6]

**Comment by andrewvmail** [comment]
curious how does this feature work? is this dialing from the native call log ?

**Comment by D-Marc1** [comment]
I can see the confusion, but in reality, all this would do is get rid of the modal that asks if you want to call that number. This way you can make your own call UI and call directly on your app without that middle step. It'll then actually do a phone call, so it'll end up in the native call log. I hope I cleared this up.

**Comment by andrewvmail** [comment]
Ah gotcha deeplink?

**Comment by dmarcs** [comment]
I added `sendRealCall` in v1.1.0. Now you can call an actual number like `5618770325`.

**Comment by D-Marc1** [comment]
Renamed as `callNumber`
