### ISSUE TITLE
FCM on iOS

### ISSUE THREAD

**Issue by bpowell15** [WebsiteBeaver/CordovaCall#69]
This plugin does not seem to work along side other cordova plugins which allow for the use of FCM on iOS. Has anyone been successful at implementing both? 

I have tried ionic/fcm and phonegap-plugin-push both of which function perfectly independently. Android  functions as expected but on iOS device ready will fire but the app will freeze immediately after.

Any help is greatly appreciated.

**Comment by bpowell15** [comment]
bump bump bump

**Comment by Bobisback** [comment]
Did you ever make any progress on this?

**Comment by bpowell15** [comment]
@Bobisback yes, VOIP doesnt work with fcm. You have to use APNs directly or a different push notification service.. i believe AWS supports VOIP as well.

**Comment by Bobisback** [comment]
Okie dokie, @bpowell15 any guides you can link by chance that will walk through this process?

**Comment by AleksandarTokarev** [comment]
Amazon SNS (Simple Notification Service) works with VOIP Pushes for Apple. We are using it to send pushes
