### ISSUE TITLE
Control audio

### ISSUE THREAD

**Issue by D-Marc1** [WebsiteBeaver/CordovaCall#7]
Programmatically control muting and speakerphone on/off.

**Comment by dmarcs** [comment]
Added in 1.0.8. You can now call `mute()`, `unmute()`, `speakerPhoneOn()`, `speakerPhoneOff()`. The only problem is that `mute()` and `unmute()` only work on certain iOS devices as explained in the `isInputGainSettable` docs [https://developer.apple.com/documentation/avfoundation/avaudiosession/1616502-isinputgainsettable](https://developer.apple.com/documentation/avfoundation/avaudiosession/1616502-isinputgainsettable)

If a device doesn't support muting/unmuting, then it's best to just mute/unmute using WebRTC.

**Comment by dmarcs** [comment]
I also added `onMute` and `onUnmute` events in 1.0.9, but they only work for iOS.
