### ISSUE TITLE
Crash on Android and not correct at all on IOS

### ISSUE THREAD

**Issue by jwliang1226** [WebsiteBeaver/CordovaCall#8]
I use this plugin for IOS and Android.

Test on iphone6s Plus, IOS11.1
IOS: Plugin cannot function normally when I sendCall and receiveCall.
CASE1 (sendCall): No screen pop up until I close my app then it pop up.
CASE2 (receiveCall): 
    The screen pop up normally, I click the "Accept icon" will return back my app screen and then  I close my app the calling screen pop up.

Android: App will crash when I sendCall. 
"test.test.test" is app name. 
Android SDK:  API_26
Run at Android 5.1 Lollipop

adb logcat:
E/AndroidRuntime(16600): java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
V/SettingsInterface(  850):  from settings cache , name = send_action_app_error , value = 1
D/ViewRootImpl(  850): hardware acceleration is enabled, this = ViewRoot{20af8a0d Application Error: test.test.test,ident = 108}
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ registerInputChannel - monitor=false
V/WindowManager(  850): Changing focus from null to Window{b2187d3 u0 Application Error: test.test.test} Callers=com.android.server.wm.WindowManagerService.addWindow:2989 com.android.server.wm.Session.addToDisplay:174 android.view.ViewRootImpl.setView:641 android.view.WindowManagerGlobal.addView:289 
D/InputDispatcher(  850): Focus entered window: Window{b2187d3 u0 Application Error: test.test.test}
I/WindowManager(  850): Gaining focus: Window{b2187d3 u0 Application Error: test.test.test}
I/BufferQueueConsumer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:0,p:-1,c:320) setConsumerName: Application Error: test.test.test
I/BufferQueueConsumer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:0,p:-1,c:320) setDefaultBufferSize: width=193 height=193
I/BufferQueueConsumer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:0,p:-1,c:320) setDefaultBufferSize: width=1218 height=624
I/BufferQueueProducer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:1,p:850,c:320) connect(P): api=1 producer=(850:system_server) producerControlledByApp=false
D/BufferQueueProducer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:1,p:850,c:320) allocateBuffers: allocating from 0 buffers up to 4 buffers
D/BufferQueueProducer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:1,p:850,c:320) allocateBuffers: allocating from 4 buffers up to 4 buffers
I/BufferQueueProducer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:1,p:850,c:320) queueBuffer: fps=2.98 dur=1005.45 max=985.90 min=6.88
W/RefreshRateControl(  850): Open RRC Driver Error (No such file or directory)
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ prepareDispatchCycle - flags=0x00000105, xOffset=-27.000000, yOffset=-709.000000, scaleFactor=1.000000, pointerIds=0x80000000
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ startDispatchCycle
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ finishDispatchCycle - seq=47750, handled=true
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ startDispatchCycle
I/BufferQueueProducer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:1,p:850,c:320) queueBuffer: fps=17.13 dur=1518.05 max=1068.03 min=8.10
W/RefreshRateControl(  850): Open RRC Driver Error (No such file or directory)
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ prepareDispatchCycle - flags=0x00000105, xOffset=-27.000000, yOffset=-709.000000, scaleFactor=1.000000, pointerIds=0x80000000
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ startDispatchCycle
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ finishDispatchCycle - seq=47752, handled=true
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ startDispatchCycle
V/WindowManager(  850): Changing focus from Window{b2187d3 u0 Application Error: test.test.test EXITING} to Window{3f245d3e u0 com.sonyericsson.home/com.sonymobile.home.HomeActivity} Callers=com.android.server.wm.WindowManagerService.removeWindowLocked:3121 com.android.server.wm.WindowManagerService.removeWindow:3058 com.android.server.wm.Session.remove:193 android.view.ViewRootImpl.dispatchDetachedFromWindow:3451 
I/WindowManager(  850): Losing focus: Window{b2187d3 u0 Application Error: test.test.test EXITING}
I/BufferQueueProducer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:1,p:-1,c:320) disconnect(P): api 1
I/BufferQueueConsumer(  320): [Application Error: test.test.test](this:0x7f6c18a000,id:908,api:1,p:-1,c:320) getReleasedBuffers: returning mask 0xffffffffffffffff
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ unregisterInputChannel
D/InputDispatcher(  850): channel 'b2187d3 Application Error: test.test.test (server)' ~ abortBrokenDispatchCycle - notify=false
D/InputDispatcher(  850): Focus left window: Window{b2187d3 u0 Application Error: test.test.test}
D/InputDispatcher(  850): Window went away: Window{b2187d3 u0 Application Error: test.test.test}
D/Dialog  (  850): handleMessage:{ when=0 what=67 obj=com.android.server.am.AppErrorDialog$2@37848bcd target=android.app.Dialog$ListenersHandler obj=com.android.server.am.AppErrorDialog$2@37848bcd }

Nice plugin and thank you review it.

**Comment by D-Marc1** [comment]
Hey @jwliang1226, we'd love to help you out. Can you please try this plugin on a new blank Cordova project and see if it works? I just want to see if it's because of another plugin conflicting with it.

**Comment by dmarcs** [comment]
Thanks for sending the error log for Android. I'll take a look at it, and will get back to you if I figure it out.

The iOS problems that you're reporting aren't bugs. I can see why you don't like it, but that's just how Apple CallKit works. Take a look at https://www.youtube.com/watch?v=06svKrE1lJ8 for a demo. When you call `receiveCall` you'll get the incoming call UI. Then you can press accept, which takes you back to your app. The call UI still runs, and you can see this by either

1) pressing the power button
2) double clicking the home button

The same is true for `sendCall`. Once you call this method, it looks like nothing happened, but when you press the power button you'll see the call UI. Instead of pressing the power button, you can click the home button and you'll see a green bar at the top indicating that the call is in progress.

Download Facebook Messenger, and you'll see that this is how CallKit works. Once you finish making your video or audio chat, you'll understand why CallKit works this way. It actually makes a lot of sense, just not at first.

**Comment by dmarcs** [comment]
Unfortunately you can't do that with CallKit. The correct way to do this is to making your own outgoing call screen using HTML because like you said the user can't tell when an outgoing call is made (without tapping home or power).
